$hypr = ~/.local/share/caelestia/hypr
$hl = $hypr/hyprland
$cConf = ~/.config/caelestia

# Variables (colours + other vars)
exec = cp -L --no-preserve=mode --update=none $hypr/scheme/default.conf $hypr/scheme/current.conf
source = $hypr/scheme/current.conf
source = $hypr/variables.conf

# User variables
exec = mkdir -p $cConf && touch -a $cConf/hypr-vars.conf
source = $cConf/hypr-vars.conf

# Default monitor conf
# monitor = , preferred, auto, 1
# laptop on the right
monitor=DP-1, 1920x1080@60, 0x0, 1
monitor=HDMI-A-1, 3440x1440@100, 1920x0, 1
# monitor = name, addreserved, TOP, BOTTOM, LEFT, RIGHT
# monitor=HDMI-A-1, addreserved, 0, 0, 440, 440 # for streaming purposes so that I get 1080p size
monitor=eDP-1, 1920x1080@300, 5360x0, 1
# laptop on the left
# monitor=eDP-1, 1920x1080@300, 0x0, 1
# monitor=HDMI-A-1, 3440x1440@100, 1920x0, 1


# Configs
source = $hl/env.conf
source = $hl/general.conf
source = $hl/input.conf
source = $hl/misc.conf
source = $hl/animations.conf
source = $hl/decoration.conf
source = $hl/group.conf
source = $hl/execs.conf
source = $hl/rules.conf
source = $hl/gestures.conf
source = $hl/keybinds.conf

# User configs
exec = mkdir -p $cConf && touch -a $cConf/hypr-user.conf
source = $cConf/hypr-user.conf
exec-once = caelestia scheme set -n dynamic
exec-once = hyprpm reload -n
exec-once = /usr/bin/hyprland-per-window-layout
exec-once = caelestia wallpaper -r ~/Картинки/wallhaven/ # random wallpaper from a folder
