# ### Hyprland ###
# Apps
$terminal = wezterm
$browser = zen-browser
$editor = codium
$fileExplorer = nemo

# Touchpad
$touchpadDisableTyping = true
$touchpadScrollFactor = 0.3
$workspaceSwipeFingers = 4
$gestureFingers = 3
$gestureFingersMore = 4

# Blur
$blurEnabled = true
$blurSpecialWs = false
$blurPopups = true
$blurInputMethods = true
$blurSize = 8
$blurPasses = 2
$blurXray = false

# Shadow
$shadowEnabled = true
$shadowRange = 20
$shadowRenderPower = 3
$shadowColour = rgba($surfaced4)

# Gaps
$workspaceGaps = 8
$windowGapsIn = 8
$windowGapsOut = 16
$singleWindowGapsOut = 4

# Window styling
$windowOpacity = 0.95
$windowRounding = 12

$windowBorderSize = 3
$activeAlpha = e6
$inactiveAlpha = c4
$activeWindowBorderColour = rgba($primary$activeAlpha) rgba($knegative$activeAlpha) 45deg
$inactiveWindowBorderColour = rgba($onPrimaryFixedVariant$inactiveAlpha) rgba($onTertiaryFixedVariant$inactiveAlpha) 45deg

# Misc
$volumeStep = 5  # In percent
$cursorTheme = sweet-cursors
$cursorSize = 24


# ### Keybinds ###
# Workspaces
$kbMoveWinToWs = Super+Shift
$kbMoveWinToWsGroup = Ctrl+Super+Alt
$kbGoToWs = Super
$kbGoToWsGroup = Ctrl+Super

$kbNextWs = Ctrl+Super, right
$kbPrevWs = Ctrl+Super, left

$kbToggleSpecialWs = Super, S

# Window groups
$kbWindowGroupCycleNext = Alt, Tab
$kbWindowGroupCyclePrev = Shift+Alt, Tab
$kbUngroup = Super, U
$kbToggleGroup = Super, Comma

# Window actions
$kbMoveWindow = Super, Z
$kbResizeWindow = Super, X
$kbWindowPip = Super+Alt, Backslash
$kbPinWindow = Super, P
$kbWindowFullscreen = Super, F
$kbWindowBorderedFullscreen = Super+Alt, F
$kbToggleWindowFloating = Super+Alt, Space
$kbCloseWindow = Super, Q

# Special workspace toggles
$kbSystemMonitor = Ctrl+Shift, Escape
$kbMusic = Super, M
$kbCommunication = Super, D
$kbTodo = Super, R

# Apps
$kbTerminal = Super, T
$kbBrowser = Super, W
$kbEditor = Super, C
$kbFileExplorer = Super, E

# Misc
$kbSession = Ctrl+Alt, Delete
$kbClearNotifs = Ctrl+Alt, C
$kbShowPanels = Super, K
$kbLock = Super+Shift+Ctrl, L
$kbRestoreLock = Super+Alt, L
